import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  consumes: ["application/json"],
  produces: ["application/json"],
};

const outputFile = "./swagger-output.json";
const routes = [
  "./src/routes/authRoute.js",
  "./src/routes/recipeRoute.js",
  "./src/routes/userRoutes.js",
];

swaggerAutogen(outputFile, routes, doc).then(() => {
  require("./server");
});
