name: Node.js

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Upgrade to v3 for Node.js 20 support

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4 # Upgrade to v3 for Node.js 20 support
        with:
          node-version: 20.

      - name: Install dependencies
        run: |
          npm install
          npm run build
